service: ims
frameworkVersion: '3'

custom:
  common: ${file(./serverless.common.yml):custom}
  serverless-layers:
    dependenciesPath: ./package.json
    layersDeploymentBucket: ${self:custom.common.artifactBucket}

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-1
  stage: ${env:ENV, 'dev'}
    
package:
  exclude:
    - node_modules
  patterns:
    - '!package-lock.json'
    - '!yarn.lock'

functions:
  - ${file(src/handlers/ims/function.yml)}

plugins: ${file(yml/plugins.yml):plugins}
resources: ${file(yml/resources.yml)}
